import type { Answer, Question } from "./validation";
import type { AIContextInputItem } from "@/components/ui/AIContextPanel";
import { pick, type Locale } from "./i18n";

/** Centralizes the copy shown in AIContextPanel across all 4 generation steps, so UI strings
 * live in exactly one place instead of being retyped per page (same division of labor as
 * STATE_LABELS: copy lives here, each page decides which inputs/principles apply to it). */

export function truncate(text: string, max = 100): string {
  const trimmed = text.trim();
  return trimmed.length > max ? `${trimmed.slice(0, max).trimEnd()}…` : trimmed;
}

export function transcriptInput(locale: Locale = "en"): AIContextInputItem {
  return { label: pick(locale, "Call transcript", "Transcript van gesprek"), present: true };
}

export function notesInput(notes: string | null, opts?: { href?: string }, locale: Locale = "en"): AIContextInputItem {
  return {
    label: pick(locale, "Consultant notes", "Notities van consultant"),
    present: !!notes?.trim(),
    detail: notes?.trim() ? truncate(notes) : undefined,
    absentText: pick(locale, "No notes added yet", "Nog geen notities toegevoegd"),
    href: notes?.trim() ? opts?.href : undefined,
    linkLabel: pick(locale, "View notes", "Notities bekijken"),
  };
}

export function sourceSystemInput(sourceSystem?: string, locale: Locale = "en"): AIContextInputItem {
  return {
    label: pick(locale, "Source system", "Bronsysteem"),
    present: !!sourceSystem,
    detail: sourceSystem,
    absentText: pick(locale, "No source system specified", "Geen bronsysteem opgegeven"),
  };
}

export function answersInput(
  label: string,
  questions: Question[],
  answers: Answer[],
  href: string,
  locale: Locale = "en",
): AIContextInputItem {
  const answeredCount = questions.filter((q) => answers.find((a) => a.questionId === q.id)?.answer?.trim()).length;
  return {
    label,
    present: true,
    detail: pick(locale, `${answeredCount} of ${questions.length} answered`, `${answeredCount} van ${questions.length} beantwoord`),
    href,
    linkLabel: pick(locale, "View answers", "Antwoorden bekijken"),
  };
}

export function finalProposalInput(version: number, href: string, locale: Locale = "en"): AIContextInputItem {
  return { label: pick(locale, "The finalized proposal", "Het definitieve voorstel"), present: true, detail: `v${version}`, href, linkLabel: pick(locale, "View proposal", "Voorstel bekijken") };
}

export function examplesInput(count: number, locale: Locale = "en"): AIContextInputItem {
  return {
    label: pick(locale, "Previously approved proposals", "Eerder goedgekeurde voorstellen"),
    present: count > 0,
    detail: count > 0 ? pick(locale, `${count}, for tone and structure only`, `${count}, alleen voor toon en structuur`) : undefined,
    absentText: pick(locale, "No previous proposals available yet", "Nog geen eerdere voorstellen beschikbaar"),
  };
}

export function sampleDataInput(locale: Locale = "en"): AIContextInputItem {
  return {
    label: pick(locale, "Illustrative sample data", "Illustratieve voorbeelddata"),
    present: true,
    detail: pick(locale, "generated by the system from the data model the AI designs — no real client figures", "door het systeem gegenereerd vanuit het datamodel van de AI — geen echte klantcijfers"),
  };
}

export const QUESTIONS1_PRINCIPLES: string[] = [
  "Picks one concrete problem to dig into — even when several topics come up.",
  "Doesn't ask questions the transcript, notes, or source system already answer.",
  "Focuses on the gaps that improve the proposal most: how it works today, how much time it takes, which systems are involved.",
];

export const PROPOSAL_PRINCIPLES: string[] = [
  "Scopes the proposal to that one problem — no broad approach.",
  "Never makes up a specific amount — the investment stays a placeholder until a scoping call.",
  "Writes short and concrete, without vague buzzwords.",
];

export const PROPOSAL_EXAMPLES_PRINCIPLE =
  "Uses previously approved proposals for tone and structure only — client details from them are never copied.";

export const QUESTIONS2_PRINCIPLES: string[] = [
  "Stays close to the one problem from the proposal — no broad spread of reports.",
  "Asks which numbers will convince this client and what a good 'before vs. after' story looks like.",
  "Doesn't ask about the source system again if it's already known.",
];

export const DASHBOARD_PRINCIPLES: string[] = [
  "Designs a data model and page for this one problem, in the client's own words.",
  "Writes no numbers on the dashboard itself — the system generates the sample data and calculates everything.",
  "Only uses figures stated literally in the transcript, notes, or answers, with a quote; others are left out.",
  "Doesn't invent a target: without a stated target, the dashboard compares against the average or the previous period.",
  "Only picks from the fixed Power BI layouts in the Datavance brand style.",
];
